-- Add social media URLs to site settings
ALTER TABLE `SiteSettings`
ADD COLUMN `facebook` VARCHAR(191) NULL,
ADD COLUMN `instagram` VARCHAR(191) NULL,
ADD COLUMN `x` VARCHAR(191) NULL,
ADD COLUMN `pinterest` VARCHAR(191) NULL,
ADD COLUMN `youtube` VARCHAR(191) NULL,
ADD COLUMN `linkedin` VARCHAR(191) NULL,
ADD COLUMN `tiktok` VARCHAR(191) NULL;
